# Secret Manager (SDD §4.7). Replicated only in the primary region (CON-5).
#
# * workweek-si-pat / hr-backend-tokens: created EMPTY here. Values are pushed from the
#   local, gitignored .env by `deployment/deploy.sh push-secrets` so a vendor PAT never
#   appears in Terraform variables or state.
# * HMAC keys: generated by Terraform (random_password) — they live in tfstate, which is
#   a private, versioned GCS bucket. Acceptable for MVP synthetic data (SDD §2.2).

locals {
  secret_replica = var.region
}

resource "google_secret_manager_secret" "vendor_pat" {
  secret_id = "workweek-si-pat"
  replication {
    user_managed {
      replicas {
        location = local.secret_replica
      }
    }
  }
  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret" "vendor_tokens" {
  count     = var.enable_per_persona_tokens ? 1 : 0
  secret_id = "hr-backend-tokens"
  replication {
    user_managed {
      replicas {
        location = local.secret_replica
      }
    }
  }
  depends_on = [google_project_service.apis]
}

resource "random_password" "envelope" {
  length  = 48
  special = false
}

resource "random_password" "confirm" {
  length  = 48
  special = false
}

resource "google_secret_manager_secret" "envelope" {
  secret_id = "hr-identity-envelope-key"
  replication {
    user_managed {
      replicas {
        location = local.secret_replica
      }
    }
  }
  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "envelope" {
  secret      = google_secret_manager_secret.envelope.id
  secret_data = random_password.envelope.result
}

resource "google_secret_manager_secret" "confirm" {
  secret_id = "hr-confirm-token-key"
  replication {
    user_managed {
      replicas {
        location = local.secret_replica
      }
    }
  }
  depends_on = [google_project_service.apis]
}

resource "google_secret_manager_secret_version" "confirm" {
  secret      = google_secret_manager_secret.confirm.id
  secret_data = random_password.confirm.result
}

# ---- access: shared HMAC keys -> both services; vendor PAT(s) -> ACL only
resource "google_secret_manager_secret_iam_member" "shared" {
  for_each = {
    envelope_agent = [google_secret_manager_secret.envelope.id, google_service_account.agent.email]
    envelope_acl   = [google_secret_manager_secret.envelope.id, google_service_account.acl.email]
    confirm_agent  = [google_secret_manager_secret.confirm.id, google_service_account.agent.email]
    confirm_acl    = [google_secret_manager_secret.confirm.id, google_service_account.acl.email]
    pat_acl        = [google_secret_manager_secret.vendor_pat.id, google_service_account.acl.email]
  }
  secret_id = each.value[0]
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${each.value[1]}"
}

resource "google_secret_manager_secret_iam_member" "tokens_acl" {
  count     = var.enable_per_persona_tokens ? 1 : 0
  secret_id = google_secret_manager_secret.vendor_tokens[0].id
  role      = "roles/secretmanager.secretAccessor"
  member    = "serviceAccount:${google_service_account.acl.email}"
}
